/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as Tours1HourRouteImport } from './routes/tours.1-hour'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const Tours1HourRoute = Tours1HourRouteImport.update({
  id: '/tours/1-hour',
  path: '/tours/1-hour',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/tours/1-hour': typeof Tours1HourRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/tours/1-hour': typeof Tours1HourRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/tours/1-hour': typeof Tours1HourRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/tours/1-hour'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/tours/1-hour'
  id: '__root__' | '/' | '/tours/1-hour'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  Tours1HourRoute: typeof Tours1HourRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tours/1-hour': {
      id: '/tours/1-hour'
      path: '/tours/1-hour'
      fullPath: '/tours/1-hour'
      preLoaderRoute: typeof Tours1HourRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  Tours1HourRoute: Tours1HourRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
