/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as McpRouteImport } from './routes/mcp'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ToursVipRouteImport } from './routes/tours.vip'
import { Route as Tours3HoursRouteImport } from './routes/tours.3-hours'
import { Route as Tours2HoursRouteImport } from './routes/tours.2-hours'
import { Route as Tours1HourRouteImport } from './routes/tours.1-hour'
import { Route as Char91DotwellKnownChar93OauthProtectedResourceRouteImport } from './routes/[.well-known]/oauth-protected-resource'
import { Route as Char91DotmcpChar93ListToolsRouteImport } from './routes/[.mcp]/list-tools'
import { Route as Char91DotmcpChar93InvokeToolToolRouteImport } from './routes/[.mcp]/invoke-tool/$tool'

const McpRoute = McpRouteImport.update({
  id: '/mcp',
  path: '/mcp',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ToursVipRoute = ToursVipRouteImport.update({
  id: '/tours/vip',
  path: '/tours/vip',
  getParentRoute: () => rootRouteImport,
} as any)
const Tours3HoursRoute = Tours3HoursRouteImport.update({
  id: '/tours/3-hours',
  path: '/tours/3-hours',
  getParentRoute: () => rootRouteImport,
} as any)
const Tours2HoursRoute = Tours2HoursRouteImport.update({
  id: '/tours/2-hours',
  path: '/tours/2-hours',
  getParentRoute: () => rootRouteImport,
} as any)
const Tours1HourRoute = Tours1HourRouteImport.update({
  id: '/tours/1-hour',
  path: '/tours/1-hour',
  getParentRoute: () => rootRouteImport,
} as any)
const Char91DotwellKnownChar93OauthProtectedResourceRoute =
  Char91DotwellKnownChar93OauthProtectedResourceRouteImport.update({
    id: '/.well-known/oauth-protected-resource',
    path: '/.well-known/oauth-protected-resource',
    getParentRoute: () => rootRouteImport,
  } as any)
const Char91DotmcpChar93ListToolsRoute =
  Char91DotmcpChar93ListToolsRouteImport.update({
    id: '/.mcp/list-tools',
    path: '/.mcp/list-tools',
    getParentRoute: () => rootRouteImport,
  } as any)
const Char91DotmcpChar93InvokeToolToolRoute =
  Char91DotmcpChar93InvokeToolToolRouteImport.update({
    id: '/.mcp/invoke-tool/$tool',
    path: '/.mcp/invoke-tool/$tool',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/mcp': typeof McpRoute
  '/.mcp/list-tools': typeof Char91DotmcpChar93ListToolsRoute
  '/.well-known/oauth-protected-resource': typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  '/tours/1-hour': typeof Tours1HourRoute
  '/tours/2-hours': typeof Tours2HoursRoute
  '/tours/3-hours': typeof Tours3HoursRoute
  '/tours/vip': typeof ToursVipRoute
  '/.mcp/invoke-tool/$tool': typeof Char91DotmcpChar93InvokeToolToolRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/mcp': typeof McpRoute
  '/.mcp/list-tools': typeof Char91DotmcpChar93ListToolsRoute
  '/.well-known/oauth-protected-resource': typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  '/tours/1-hour': typeof Tours1HourRoute
  '/tours/2-hours': typeof Tours2HoursRoute
  '/tours/3-hours': typeof Tours3HoursRoute
  '/tours/vip': typeof ToursVipRoute
  '/.mcp/invoke-tool/$tool': typeof Char91DotmcpChar93InvokeToolToolRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/mcp': typeof McpRoute
  '/.mcp/list-tools': typeof Char91DotmcpChar93ListToolsRoute
  '/.well-known/oauth-protected-resource': typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  '/tours/1-hour': typeof Tours1HourRoute
  '/tours/2-hours': typeof Tours2HoursRoute
  '/tours/3-hours': typeof Tours3HoursRoute
  '/tours/vip': typeof ToursVipRoute
  '/.mcp/invoke-tool/$tool': typeof Char91DotmcpChar93InvokeToolToolRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/mcp'
    | '/.mcp/list-tools'
    | '/.well-known/oauth-protected-resource'
    | '/tours/1-hour'
    | '/tours/2-hours'
    | '/tours/3-hours'
    | '/tours/vip'
    | '/.mcp/invoke-tool/$tool'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/mcp'
    | '/.mcp/list-tools'
    | '/.well-known/oauth-protected-resource'
    | '/tours/1-hour'
    | '/tours/2-hours'
    | '/tours/3-hours'
    | '/tours/vip'
    | '/.mcp/invoke-tool/$tool'
  id:
    | '__root__'
    | '/'
    | '/mcp'
    | '/.mcp/list-tools'
    | '/.well-known/oauth-protected-resource'
    | '/tours/1-hour'
    | '/tours/2-hours'
    | '/tours/3-hours'
    | '/tours/vip'
    | '/.mcp/invoke-tool/$tool'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  McpRoute: typeof McpRoute
  Char91DotmcpChar93ListToolsRoute: typeof Char91DotmcpChar93ListToolsRoute
  Char91DotwellKnownChar93OauthProtectedResourceRoute: typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  Tours1HourRoute: typeof Tours1HourRoute
  Tours2HoursRoute: typeof Tours2HoursRoute
  Tours3HoursRoute: typeof Tours3HoursRoute
  ToursVipRoute: typeof ToursVipRoute
  Char91DotmcpChar93InvokeToolToolRoute: typeof Char91DotmcpChar93InvokeToolToolRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/mcp': {
      id: '/mcp'
      path: '/mcp'
      fullPath: '/mcp'
      preLoaderRoute: typeof McpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tours/vip': {
      id: '/tours/vip'
      path: '/tours/vip'
      fullPath: '/tours/vip'
      preLoaderRoute: typeof ToursVipRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tours/3-hours': {
      id: '/tours/3-hours'
      path: '/tours/3-hours'
      fullPath: '/tours/3-hours'
      preLoaderRoute: typeof Tours3HoursRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tours/2-hours': {
      id: '/tours/2-hours'
      path: '/tours/2-hours'
      fullPath: '/tours/2-hours'
      preLoaderRoute: typeof Tours2HoursRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tours/1-hour': {
      id: '/tours/1-hour'
      path: '/tours/1-hour'
      fullPath: '/tours/1-hour'
      preLoaderRoute: typeof Tours1HourRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/.well-known/oauth-protected-resource': {
      id: '/.well-known/oauth-protected-resource'
      path: '/.well-known/oauth-protected-resource'
      fullPath: '/.well-known/oauth-protected-resource'
      preLoaderRoute: typeof Char91DotwellKnownChar93OauthProtectedResourceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/.mcp/list-tools': {
      id: '/.mcp/list-tools'
      path: '/.mcp/list-tools'
      fullPath: '/.mcp/list-tools'
      preLoaderRoute: typeof Char91DotmcpChar93ListToolsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/.mcp/invoke-tool/$tool': {
      id: '/.mcp/invoke-tool/$tool'
      path: '/.mcp/invoke-tool/$tool'
      fullPath: '/.mcp/invoke-tool/$tool'
      preLoaderRoute: typeof Char91DotmcpChar93InvokeToolToolRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  McpRoute: McpRoute,
  Char91DotmcpChar93ListToolsRoute: Char91DotmcpChar93ListToolsRoute,
  Char91DotwellKnownChar93OauthProtectedResourceRoute:
    Char91DotwellKnownChar93OauthProtectedResourceRoute,
  Tours1HourRoute: Tours1HourRoute,
  Tours2HoursRoute: Tours2HoursRoute,
  Tours3HoursRoute: Tours3HoursRoute,
  ToursVipRoute: ToursVipRoute,
  Char91DotmcpChar93InvokeToolToolRoute: Char91DotmcpChar93InvokeToolToolRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
